---

- name: Install default gems prerequisite packages
  apt:
    name={{ item.name }}={{ item.version }} 
    state=present 
    update_cache=yes 
    cache_valid_time=3600 
    install_recommends=no
  with_items: "{{ default_gemset.prereq_pkgs }}"
  become: true

- name: Install default gems
  shell: "{{gem}} install {{ item.name }} -v {{ item.version }}"
  args:
    executable: /bin/bash
  with_items: "{{ default_gemset.gems }}"

